Refactor build script to add constants for easier setup
romangraef/Forge1.8.9Template pull request #10
Opened 2023-05-12 18:36 UTC by walkerselby

Add constants
Refactor build to use constants
Update ReadMe to reflect changes

2023-05-13 16:47 UTC, romangraef requested changes

2023-05-13 16:47 UTC, romangraef commented on build.gradle.kts
> +    duplicatesStrategy = DuplicatesStrategy.INCLUDE
I don't think you need that duplicates strategy. If you do, then that is probably a hint that you are reading the resource folder twice, which means there is some other misconfiguration. IF this is really needed, I would want a comment here justifying the usage.

2023-05-13 16:47 UTC, romangraef commented on build.gradle.kts
> +    mappings("de.oceanlabs.mcp:mcp_stable:22-$mcVersion")
Different minecraft versions need different mcp mappings.
For 1.8.9 and 1.12 you can use https://repo.nea.moe/#/releases/moe/nea/mcp/mcp-yarn if you *just* want `mcVersion` as dependency version, but if you want actual MCP (not my repack) then you will need `22-1.8.9` for 1.8.9 and `39-1.12` for 1.12. I don't know the versions for 1.10 of the top of my head (which is the only other popular version that this template would work for, 1.7.X and 1.13.X are broken with this template, and 1.9 and 1.11 arent popular to mod on).

2023-05-13 16:47 UTC, romangraef commented on build.gradle.kts
> +    forge("net.minecraftforge:forge:$mcVersion-11.15.1.2318-$mcVersion")
Different minecraft versions need different forge versions.
For 1.8.9 it's `11.15.1.2318` and for 1.12.2 it's `14.21.1.2443` and for 1.10 it's `12.18.0.2000`.

2023-05-13 16:47 UTC, romangraef commented on README.md
> +the `build.gradle.kts` at the lines specified with comments.
Even with these buildscript changes you will still need to delete the package (otherwise it will not compile).

2023-05-13 16:47 UTC, romangraef commented on README.md
> +In `settings.gradle.kts` change `rootProject.name` to your desired mod id.
I would put these properties into the `gradle.properties` and then use 
```kt
val baseGroup: String by project
// or (in the settings.gradle.kts)
val baseGroup: String by settings 
``` 
in the actual buildscript, that way only one file needs to be changed (and the properties file is easier to change).

Also the `com.example` package needs to be renamed to `$baseGroup` and the mixin file needs to be renamed, or mixins will break.

2023-05-13 16:47 UTC, romangraef commented on build.gradle.kts
>  version = "1.0.0"
While you are here, you could also pull the `version` into a `gradle.properties` property

2023-05-13 16:47 UTC, romangraef commented on build.gradle.kts
> +group = "$baseGroup.archloomtemplate"
I wouldn't add the `.archloomtemplate` here.

2023-05-15 16:56 UTC, walkerselby commented on build.gradle.kts
> +    mappings("de.oceanlabs.mcp:mcp_stable:22-$mcVersion")
Yeah, and these are not likely to change often -- will just leave them hardcoded.

2023-05-15 19:06 UTC, romangraef requested changes

2023-05-15 19:06 UTC, romangraef commented on build.gradle.kts
> +    //replace stuff in mcmod.info, nothing else
This is also replacing info in the mixins file:
```suggestion
```

2023-05-15 19:06 UTC, romangraef commented on build.gradle.kts
> +
This is including a duplicate copy of both `mcmod.info` and `mixins.$modid.json`.
```suggestion
    filesMatching(listOf("mcmod.info", "mixins.$modid.json")) {
```

Additionally I think you are missing the actual placeholders in `src/main/resources/mcmod.info` that would be replaced by this operation:

```json
[
  {
	"modid": "${modid}",
	"name": "Xample Mod",
	"description": "A mod that is used as an example.",
	"version": "${version}",
	"mcversion": "1.8.9",
	"url": "https://github.com/romangraef/Forge1.8.9Template/",
	"updateUrl": "",
	"authorList": [
	  "You"
	],
	"credits": "",
	"logoFile": "",
	"screenshots": [],
	"dependencies": []
  }
]
```

2023-05-25 00:21 UTC, romangraef requested changes

2023-05-25 00:21 UTC, romangraef commented on gradle.properties
> +version = "1.0.0"
I don't think these properties should be quoted: 

```json
[
  {
    "modid": "examplemod",
    "name": "Xample Mod",
    "description": "A mod that is used as an example.",
    "version": ""1.0.0"",
``` 

```suggestion
mcVersion = 1.8.9
version = 1.0.0
```

2023-05-25 00:21 UTC, romangraef commented on gradle.properties
> +version = "1.0.0"
Aside from this, this pr looks ready.

2023-05-25 00:21 UTC, walkerselby commented
Thanks for the feedback!

2023-05-25 00:26 UTC, romangraef commented
Merged in https://github.com/romangraef/Forge1.8.9Template/commit/7e8fa83e5afc0b21c96b91bbe87f39751e841bf7

2023-05-25 00:26 UTC, closed without merging